main/adminEdit/__init__.py
from flask import Blueprint

adminEdit = Blueprint('adminEdit',__name__)

from main.adminEdit import views

main/adminEdit/views.py


from flask import Blueprint, render_template, request 
import re
from main.dbCon.dbAdminEdit import dbAdminEdit
from main.pubCore.userVerification import Superadmin_request

from main.adminEdit import adminEdit


@adminEdit.route('/adminEdit')
@Superadmin_request
def Default():
    return render_template(
         'AdminEdit.html',
         title= '秋霜飞晚',
         dataList = '',
        )


@adminEdit.route('/adminEdit/startdb', methods =['POST'])
def startdb():
    tablename = ''
    cloumList = request.form.to_dict()
    getList = []
    for (key, value) in cloumList.items():
        if re.match(r'tablename',key):
            tablename = value
        if re.match(r'careateCloum',key):
            getList.append(value)
    if tablename != '' and len(getList) > 0 :
        conn = dbAdminEdit()
        conn.creatTable(tablename,getList)
    return render_template(
            'AdminEdit.html',
            title = '秋霜飞晚',
            message = 'Create is ok',
            dataList = '',
        ).encode('utf-8')

@adminEdit.route('/adminEdit/insertdb', methods=['POST'])
def insertData():
    
    tableText = request.form['sqlText']
    if tableText!= '':
        conn = dbAdminEdit()
        num = conn.inster(tableText)
        givemessage = ['操作完了 自行检查数据']
    return render_template(
            'AdminEdit.html',
            title = '秋霜飞晚',
            message = givemessage,
            dataList = '',
        ).encode('utf-8')


@adminEdit.route('/adminEdit/searchdb', methods=['POST'])
def SearchData():
    
    tablename = request.form['tablename']
    if tablename!= '':
        conn = dbAdminEdit()
        fullTable = conn.search(tablename)
    return render_template(
            'AdminEdit.html',
            title = '秋霜飞晚',
            tname = tablename,
            columnList = fullTable[0],
            dataList = fullTable[1],
        ).encode('utf-8')




main/bookImageEdit/__init__.py
from flask import Blueprint

bookImageEdit = Blueprint('bookImageEdit',__name__)

from main.bookImageEdit import views

main/bookImageEdit/views.py
# -*- coding:utf-8 -*-
from flask import Blueprint, render_template, request , redirect, url_for,send_from_directory
import re
from main.dbCon.dbBookImageEdit import dbBookImageEdit
from main.pubCore.userVerification import admin_request
from main.bookImageEdit import bookImageEdit

from werkzeug import secure_filename
from PIL import Image 
from main.dbCon.dbErrorLog import dbErrorLog
import urllib.parse
from datetime import datetime
import random
import config
import os

@bookImageEdit.route('/bookImageEdit')
@admin_request
def default():
    return render_template(
        'BookImageEdit.html',
        title = '流年暗渡'
        )

@bookImageEdit.route('/bookImageEdit/editBook' , methods=['POST'])
def insertTBbook():
    titleName = request.form['titleName']
    contentTxt = request.form['contentTxt']
    result = 0
    try:
        db = dbBookImageEdit()
        result = db.InsetBook(titleName,contentTxt)
        message = ['保存失败','保存完了'][result > 0]
    except :
        pass
    if result> 0:
        return redirect(url_for('show.showpage',msg = '8'))





######################
@bookImageEdit.route('/fileUp', methods=['POST'])
@admin_request
def upLoad():
    file = request.files['file']
    fileSize = len(file.read())
    if float(fileSize) > config.MAX_CONTENT_LENGTH:
            Showmessage = '文件过大'
            return render_template('Backstage.html',
                title ='流年暗渡',
                url = '',
                Showmessage = Showmessage)
    else:
        if file and allowed_file(file.filename):

            #fileName = secure_filename(file.filename)
            #fileName = r_slash(file.filename) 
            dt = str(datetime.now().timestamp() /1000).replace('.','')  + str(random.randint(1,100))
            fileName = dt + getFileType(file.filename)
            size = (500,333)
            im = Image.open(file)
            im.thumbnail(size)
            try:
                im.save(os.path.join(config.UPLOAD_FOLDER,fileName))          # 保存到路径
                #file_url = config.UPLOAD_FOLDER + '\\'+ fileName
                file_url = url_for('bookImageEdit.uploaded_file', filename = fileName)   # 获取上传的文件
            except Exception  as e:
                errorlog = dbErrorLog()
                errorlog.errorLog(e,'savepicture')
                
            
            title = request.form['titleshow']
            conntent = request.form['contentshow']
            try:
                db = dbBookImageEdit()
                result = db.InsetShow(fileName,title,conntent,file_url)
                Showmessage = ['保存失败','保存完了'][result > 0]
            except Exception  as e:
                errorlog = dbErrorLog()
                errorlog.errorLog(e,'insetPicture')
        
            return render_template('BookImageEdit.html',
                 title ='流年暗渡',
                 url = file_url,
                 Showmessage = Showmessage)
        else:
            return render_template(
                'BookImageEdit.html',
                title='流年暗渡',
                Showmessage ='文件格式不正确',
                )

@bookImageEdit.route('/fileUp/<filename>')
def uploaded_file(filename):
    return send_from_directory(config.UPLOAD_FOLDER, filename)

#检查文件名称判断是否图片
def allowed_file(filename):
    return '.' in filename and filename.lower().rsplit('.',1)[1] in config.ALLOWED_EXTENSIONS

#后缀
def getFileType(filename):
    return  '.'+ filename.rsplit('.',1)[1]
    

main/pcUser/__init__.py
from flask import Blueprint

pcUser = Blueprint('pcUser',__name__)

from main.pcUser import views

main/pcUser/views.py
from flask import render_template
from main.pcUser import pcUser

@pcUser.route('/pcUser')
def showUser():
    return render_template('pcUser.html')


main/showBook/__init__.py
from flask import Blueprint

show = Blueprint('show',__name__)

from main.showBook import views

main/showBook/views.py

# -*- coding:utf-8 -*-

from flask import Blueprint, render_template, g, request 
from datetime import datetime
import math
from main.dbCon.dbShowBook import dbShowBook
from main.showBook import show

@show.route('/show', methods =['POST','GET'] )
def showpage():
    avgNum = 5  #每页显示数目
    p = request.args.get("p")  #页码
    show_first_statue = 0  #首页状态    
    if p is None:
        p = 1
    else:
        p = int(p)
        if p > 1:
            show_first_statue = 1

    limit_start = (int(p) -1) * avgNum #起始页码 每页5条

    conn = dbShowBook()
    bookList = conn.ReadBook(limit_start)
    count = conn.TotleBookNum()  #总数
    totalPage = int(math.ceil(count/avgNum)) #总页数

    dic = getPage(totalPage, p)
    return render_template(
        'showBook.html',
        title = '星庐听雨',
        bookList = bookList,
        p = int(p),
        totalPage = totalPage,
        show_first_statue = show_first_statue,
        dic_list = dic
        ).encode('utf-8')

def getPage(total, p):
    show_page = 5   #控件显示的 块
    pageoffset = 2
    start =1
    end = total

    if total> show_page:
        if p>pageoffset:
            start = p - pageoffset
            if total > p + pageoffset:
                end = p + pageoffset
            else:
                end = total
        else:
            start =1
            if total > show_page:
                end = show_page
            else :
                end = total
        if p + pageoffset > total:
            start = start -(p + pageoffset - end)
    dic = range(start, end+1)
    return dic

main/showImage/__init__.py
from flask import Blueprint

onRoad = Blueprint('onRoad',__name__)


from main.showImage import views

main/showImage/views.py

# -*- coding:utf-8 -*-

from flask import Blueprint, render_template, request, g
import sys
import math
from main.dbCon.dbShowImage import dbonRoad
from main.showImage import onRoad

@onRoad.route('/onRoad', methods=['POST','GET'])
def default():
    avgNum = 5  #每页显示数目
    p = request.args.get("p")  #页码
    show_first_statue = 0  #首页状态    
    if p is None:
        p = 1
    else:
        p = int(p)
        if p > 1:
            show_first_statue = 1

    limit_start = (int(p) -1) * avgNum #起始页码 每页5条

    db = dbonRoad()
    showList = db.showInList(limit_start)
    count = db.showTotalCount()  #总数
    totalPage = int(math.ceil(count/avgNum)) #总页数

    dic = getPage(totalPage, p)
    return render_template(
        'showImage.html',
        title = '烟雨平生',
        showPictureList = showList,
        p = int(p),
        totalPage = totalPage,
        show_first_statue = show_first_statue,
        dic_list = dic
        ).encode('utf-8')




def getPage(total, p):
    show_page = 5   #控件显示的 块
    pageoffset = 2
    start =1
    end = total

    if total> show_page:
        if p>pageoffset:
            start = p - pageoffset
            if total > p + pageoffset:
                end = p + pageoffset
            else:
                end = total
        else:
            start =1
            if total > show_page:
                end = show_page
            else :
                end = total
        if p + pageoffset > total:
            start = start -(p + pageoffset - end)
    dic = range(start, end+1)
    return dic




templates/AdminEdit.html
{% extends "layout.html" %}

{% block content %}


<div class="container body-content">

    <h2>{{ title }}</h2>

    <h2> {{message}}</h2>

    {% if columnList!= '' %}
    <table class="table table-hover">
        <caption>{{ tname }}</caption>
        <thead>
            <tr>
                {% for item in columnList  %}
                <th>{{ item }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for x in dataList %}
            <tr>
                {% for y in x %}
                <td>{{ y }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endif %}
    <div class="row clearfix">
        <!--<div class="alert alert-success">ok</div>-->

        <!-- 新增表-->
        <div class="col-md-4 column">
            <form action="/adminEdit/startdb" method="post">

                <div class="input-group" id="CreateTableGroup">
                    <label for="tableName1">创建表的名称</label>
                    <input id="tableName1" class="form-control" name="tablename" /><br />

                    <label> 字段 ：</label>
                    <button type="button" class="btn btn-info" value="添加" onclick="addCloum(this)"><span class="glyphicon glyphicon-plus"></span></button>
                </div>
                <br />
                <p>默认字段类型为varchar， 可在语法块自行创建表</p>
                <p> <button type="submit" class="btn btn-default" onclick="CloumNameCheck()">创建</button></p>
            </form>
        </div>

        <!-- 查询 -->
        <div class="col-md-4 column">
            <form action="/adminEdit/searchdb" method="post">
                <div class="form-group">
                    <label for="tableName3">查询的表名称</label>
                    <input id="tableName3" class="form-control" name="tablename" />
                </div>
                <p> <button type="submit" class="btn btn-default">查询</button></p>
            </form>
        </div>

        <!-- 文本编辑 -->
        <div class="col-md-4 column">
            <form action="/adminEdit/insertdb" method="post">
                <div class="form-group">
                    <label for="tableName2">语法</label>
                    <textarea class="form-control" rows="3" name="sqlText"></textarea>
                </div>
                <p> <button type="submit" class="btn btn-default">执行</button></p>
            </form>
        </div>









    </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript">
    function addCloum(obj) {
        
        html = "<div class='input-group centerIp'> "+
            "<label class='input-group-addon' >字段名称</label> <input id='addColumName' class='form-control' name= 'careateCloum' /> " +
            "<span class='input-group-btn'>" + 
            "<button class='btn btn-info' type='button' data-toggle='tooltip'  title='删除' id='delCloum'><span class='glyphicon glyphicon-minus'></span></button> "+
            "</span>" + 
            "</div >" 
        obj.insertAdjacentHTML('beforebegin', html)
    }

    function CloumNameCheck() {
        var CreateTableGroup = document.getElementById("CreateTableGroup");
        var list = CreateTableGroup.getElementsByTagName("input"); 
        for (var i = 1; i < list.length; i++) {
            list[i].name = "careateCloum"+ i
        }

    }

    $(document).on('click', '#delCloum', function () {
        var el = this.parentNode.parentNode
        var centerIp = $(this).parent().parent().find('#addColumName').val()
        var message = confirm('您确定要删除选中的命令')
        if (message == true) {
            el.parentNode.removeChild(el)
        }
            
    })
</script>
    {% endblock %}

templates/BookImageEdit.html
{% extends "layout.html" %}

{% block content %}


<div class="container">

    <h2>{{ title }}</h2>


    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="tabbable" >
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#panel-y" data-toggle="tab">烟雨平生</a>
                    </li>
                    <li>
                        <a href="#panel-x" data-toggle="tab">星庐听雨</a>
                    </li>
                </ul>
                <div class="tab-content">


                    <div class="tab-pane active" id="panel-y">
                        <p>烟雨平生</p>
                        {{ Showmessage }}
                        <form action="/fileUp" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="titleShow">标题</label>
                                <input id="titleShow" class="form-control" name="titleshow" /><br />
                                <label for="contentShow">正文</label>
                                <textarea id="contentShow" class="form-control" rows="3" name="contentshow"></textarea>
                            </div>

                            <input type="file" name="file"><br />
                            <button class="btn btn-default" type=submit>上传</button>
                            <img src="{{ url }}" />
                        </form>
                    </div>



                    <div class="tab-pane" id="panel-x">
                        <p>星庐听雨</p>
                        <form action="/bookImageEdit/editBook" method="post">
                            <div class="form-group">
                                <label for="title">标题</label>
                                <input id="title" class="form-control" name="titleName" /><br />
                                <label for="content">正文</label>
                                <textarea id="content" class="form-control" rows="3" name="contentTxt"></textarea>
                            </div>
                            <p> <button type="submit" class="btn btn-default">完成</button></p>
                        </form>
                    </div>


                </div>
            </div>
        </div>
        

    </div>
</div>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block content %}




<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
    <!-- zhibiao  -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- xiangmu -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="../static/image/banner2.jpg" class="img-responsive " alt="First slide">
        </div>
        <div class="item">
            <img src="../static/image/banner3.jpg" class="img-responsive " alt="Second slide">
        </div>
        <div class="item">
            <img src="../static/image/banner4.jpg" class="img-responsive " alt="Third slide">
        </div>
    </div>
    <!-- daohang -->
    <a class="carousel-control left" href="#myCarousel"
       data-slide="prev">
        &lsaquo;
    </a>
    <a class="carousel-control right" href="#myCarousel"
       data-slide="next">
        &rsaquo;
    </a>
</div>

<br />
<HR style="FILTER: progid:DXImageTransform.Microsoft.Shadow(color:#987cb9,direction:145,strength:15)" width="80%" color=#987cb9 SIZE=1>

<p class="text-center"><a href="{{ url_for('onRoad.default') }}"><span class="glyphicon glyphicon-tags"></span>&nbsp;烟雨平生</a>  <span class="glyphicon glyphicon-hand-left"></span></p>    <!-- 居中显示 -->
<div class="container body-content">


    <div class="row clearfix">
        <div class="col-md-4 column">
            {% if  showPicture|length > 0 %}
            <blockquote>
                <img src="{{ showPicture[0][4] }}" class="img-responsive center-block" /><br />
                <p>
                    {{ showPicture[0][3] }}
                </p> <small>{{showPicture[0][2]}} &nbsp;<cite>{{showPicture[0][5]}}</cite></small>
            </blockquote>
            {% else %}
            <blockquote>

                <p>
                    一曲高歌一樽酒 一人独钓一江秋
                </p> <small>深秋江畔 &nbsp;<cite></cite></small>
            </blockquote>
            {% endif %}
        </div>

        <div class="col-md-4 column">
            <blockquote>
                <p>
                    See ! Nothing
                </p> <small>Someone famous <cite>Source Title</cite></small>
            </blockquote>
        </div>

        <div class="col-md-4 column">

            <blockquote>
                <p>
                    `まだ考えている
                </p> <small> <cite>無名</cite></small>
            </blockquote>
        </div>

    </div>

    <HR style="FILTER: progid:DXImageTransform.Microsoft.Shadow(color:#987cb9,direction:145,strength:15)" width="80%" color=#987cb9 SIZE=1>

    <div class="row clearfix">
        <div class="col-md-4 col-md-offset-4">
            <!-- 偏移-->

            <div id="showEcharts" style="height:400px" >
                
            </div>
        </div>
    </div>



</div>







    {% endblock %}


    {% block scripts %}
<script src="/static/echarts/echarts.min.js"></script>
<script src="/static/echarts/echarts-wordcloud.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        

        echartsCloud();

        //仕様
        // 指定图表的配置项和数据 同步
        //var option = {
        //    title: {
        //        text: ''
        //    },
        //    tooltip: {},
        //    legend: {
        //        data: ['']
        //    },
        //    xAxis: {
        //        data: ["", "", "", "", "", ""]
        //    },
        //    yAxis: {},
        //    series: [{
        //        name: '',
        //        type: 'sunburst',
        //        data: [, , , , , ]
        //    }]
        //};

        // 使用刚指定的配置项和数据显示图表。
        //myChart.setOption(option);

    });


    function echartsCloud() {
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('showEcharts'));

        //异步之后给data
        myChart.setOption({
            title: {
                text: 'Cloud',
            },
            tooltip: {
                show: true
            },
            series: [{
                type: 'wordCloud',
                size: ['80%', '100%'],
                textRotation: [0, 45, 90, -45],
                textPadding: 0,
                autoSize: {
                    enable: true,
                    minSize: 14
                },
                textStyle: {
                    normal: {
                        fontFamily: 'sans-serif',
                        color: function () {
                            return 'rgb('
                                + [Math.round(Math.random() * 160),
                                Math.round(Math.random() * 160),
                                Math.round(Math.random() * 160)]
                                    .join(',') + ')';
                        }
                    },
                    emphasis: {
                        shadowBlur: 5,  //阴影距离  
                        shadowColor: '#333'  //阴影颜色  
                    }
                },  

                data: []
            }]
        });

        $.ajax({
            url: 'getjson',
            async: true,
            dataType: 'json',
            success: function (result) {

                myChart.setOption({

                    series: [{
                        data: result
                    }]
                });
            }
        });

        myChart.on('click', function (parmer) {
            location.href = '/show#' + parmer.name
        })
  
    }



    


</script>

    {% endblock %}

templates/layout.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>{{ title }}</title>
    <link rel="icon" href="../static/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="../static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="../static/content/site.css?v=1.0" />
    <script src="../static/scripts/modernizr-2.6.2.js"></script>


</head>

<body style="overflow-x:hidden;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">骤雨逐风</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('onRoad.default') }}">烟雨平生</a></li>
                    <li><a href="{{ url_for('show.showpage') }}">星庐听雨</a></li>
                    <li><a href="{{ url_for('bookImageEdit.default') }}">流年暗渡</a></li>
                    <li><a href="{{ url_for('adminEdit.Default') }}">秋霜飞晚</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if g.user  %}
                    <li><a data-toggle="modal"  href={{url_for('pcUser.showUser')}}><span class="glyphicon glyphicon-user"></span> {{ g.user }}</a></li>
                    <li><a data-toggle="modal" href="{{url_for('user.loginOut')}}"><span class="glyphicon glyphicon-off"></span> 登出</a></li>
                    {% else %}
                    <li><a data-toggle="modal" data-target="#register" href=""><span class="glyphicon glyphicon-cloud"></span> 注册 </a></li>
                    <li><a data-toggle="modal" data-target="#login" href=""><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
                    {% endif %}

                </ul>
            </div>



        </div>
    </div>

    {#login in #}
    <div id="login" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button class="close" data-dismiss="modal">
                        <span>&times;</span>

                    </button>

                </div>
                <div class="modal-title">
                    <h1 class="text-center">登录</h1>

                </div>
                <div class="modal-body">
                    <form class="form-group" action="/user/login" method="post">
                        <div class="form-group">
                            <label for="">用户名</label>
                            <input class="form-control" type="text" name="userName" placeholder="admin" value="admin"> 

                        </div>
                        <div class="form-group">
                            <label for="">密码    测试账号密码admin</label>
                            <input class="form-control" type="password" name="password" placeholder="">

                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary" type="submit">登录</button>
                            <button class="btn btn-danger" data-dismiss="modal">取消</button>

                        </div>
                        <a href="" data-toggle="modal" data-dismiss="modal" data-target="#register">注册</a>

                    </form>

                </div>

            </div>

        </div>

    </div>
    {# register #}
    <div id="register" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-title">
                    <h1 class="text-center">注册</h1>

                </div>
                <div class="modal-body">
                    <form class="form-group" action="/user/register" method="post">
                        <div class="form-group">
                            <label for="">用户名</label>
                            <input class="form-control" type="text" name="userName" placeholder="6-15位字母或数字">

                        </div>
                        <div class="form-group">
                            <label for="">密码</label>
                            <input class="form-control" type="password" name="password" placeholder="至少6位字母或数字">

                        </div>
                        <div class="form-group">
                            <label for="">再次输入密码</label>
                            <input class="form-control" type="password" name="passwordR" placeholder="至少6位字母或数字">

                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary" type="submit">提交</button>
                            <button class="btn btn-danger" data-dismiss="modal">取消</button>

                        </div>
                        <a href="" data-toggle="modal" data-dismiss="modal" data-target="#login">已有账号？点我登录</a>

                    </form>
                </div>
            </div>
        </div>
    </div>


    {% block content %}{% endblock %}



    <hr />
    <div class="container">
        <footer>
            <div style="width:400px;margin:0 auto; padding:10px 0;">
                <p  id="resultNum" class="text-center" style="height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">
                    
                </p>
            </div>
            
        </footer>
    </div>


    <script src="../static/scripts/jquery-1.10.2.js"></script>
    <script src="../static/scripts/bootstrap.js"></script>
    <script src="../static/scripts/respond.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            if ('{{message}}' != '') {
                alert('{{message}}')
            } else {
                var msg = getUrlParam('msg');
                switch (msg) {
                    case '1': alert('人生如梦 一樽还酹江月'); break;
                    case '2': alert('人闲桂花落 夜静春山空'); break;
                    case '3': alert('明月松间照 清泉石上流'); break;
                    case '4': alert('注册成功'); break;
                    case '5': alert('注册失败'); break;
                    case '6': alert('登录成功'); break;
                    case '7': alert('登录失败'); break;
                    case '8': alert('保存成功'); break;
                }
            }
        });


        function getUrlParam(name) {
            //构造一个含有目标参数的正则表达式对象
            var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
            //匹配目标参数
            var r = window.location.search.substr(1).match(reg);
            //返回参数值
            if (r != null) return unescape(r[2]);
            return null;
        }


        if (localStorage.pagecount) {
            localStorage.pagecount = Number(localStorage.pagecount) + 1;
        }
        else {
            localStorage.pagecount = 1;
        }
        document.getElementById("resultNum").innerHTML = '您对这个站点大概齐访问了：'+ localStorage.pagecount + ' 次这么多吧';
    </script>
    {% block scripts %}{% endblock %}

</body>
</html>

templates/pcUser.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
    

</div>
    {% endblock %}

templates/showImage.html
{% extends "layout.html" %}

{% block content %}



<div>
    <blockquote>
        <cite>烟雨平生</cite>
    </blockquote>
</div>
<div class="container body-content">


    <div class="row clearfix">
        {% if  showPictureList|length > 0 %}
        {% for x in showPictureList %}
        <div class="col-md-4 column">
            
            <blockquote>
                <img src="{{ x[4] }}" class="img-responsive center-block" /><br />
                <p>
                    {{ x[3] }}
                </p> <small>{{x[2]}} &nbsp;<cite>{{x[5]}}</cite></small>
            </blockquote>
        </div>
        {% endfor %}
        {% endif %}

    </div>

    <ul class="pagination">
        {% if show_first_statue==1 %}
        <li class=''><a href='/onRoad?p=1'>首页</a></li>
        <li class=''><a href='/onRoad?p={{p-1}}'>上一页</a></li>
        {%endif%}

        {% for dic in dic_list %}
        {% if dic==p %}
        <li class="active"><a href="/onRoad?p={{dic}}">{{dic}}</a></li>
        {%else%}
        <li><a href="/onRoad?p={{dic}}">{{dic}}</a></li>
        {%endif%}
        {%endfor%}

        {% if p < totalPage %}
        <li class=''><a href='/onRoad?p={{p+1}}'>下一页</a></li>
        <li class=''><a href='/onRoad?p={{totalPage}}'>尾页</a></li>
        {%endif%}

    </ul>
    <p>共{{totalPage}}页</p>

</div>

    {% endblock %}
